### ISSUE TITLE
Re-create the `hyp3-enterprise-test` deployment in a separate AWS account

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3#1498]
# Overview

We want to re-create our `hyp3-enterprise-test` deployment in a separate AWS account so that we can get isolated budget reports for enterprise project cost estimates.

# Tasks

Tear down the old deployment:

- [x] Set `hyp3-enterprise-test` user quotas to `0` so that no one can submit new jobs
- [x] Export and archive the contents of the `hyp3-enterprise-test` Jobs table
- [x] Delete the existing `hyp3-enterprise-test` CloudFormation stack after the new stack has been deployed (confirm that no new jobs have been run since exporting the Jobs table)

Follow our [wiki article](https://github.com/ASFHyP3/.github-private/wiki/New-HyP3-Enterprise-deployment) for new enterprise deployments, with the following modifications:

- [x] Update params in the [deployment workflow](https://github.com/ASFHyP3/hyp3/blob/develop/.github/workflows/deploy-enterprise-test.yml): `template_bucket`
- [x] Update [environment secrets](https://github.com/ASFHyP3/hyp3/settings/environments/541233468/edit) or delete and re-create the environment
- [x] Update the `hyp3-enterprise-test` DNS CNAME to point at the new deployment

**Comment by jtherrmann** [comment]
The Jobs table export is available at `s3://jth-dev/old-hyp3-enterprise-test-jobs-table.csv` in the Tools Sandbox AWS account.

**Comment by jtherrmann** [comment]
I deleted the existing stack only for it to immediately re-deploy due to a test release, so I'll just circle back and delete it again at the end of the process.

**Comment by jtherrmann** [comment]
Left off at "4. Deploy the HyP3 CI/CD stack" in the [wiki article](https://github.com/ASFHyP3/.github-private/wiki/New-HyP3-Enterprise-deployment).

**Comment by jtherrmann** [comment]
https://hyp3-enterprise-test.asf.alaska.edu is now live and returning the expected result for the `/user` endpoint.
